[font]
size = 20

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[font.normal]
family = "JetBrains Mono"
style = "Regular"
#
# [colors.primary]
# background = "0x1b182c"
# foreground = "0xcbe3e7"
#
# [colors.normal]
# black = "0x100e23"
# red = "0xff8080"
# green = "0x95ffa4"
# yellow = "0xffe9aa"
# blue = "0x91ddff"
# magenta = "0xc991e1"
# cyan = "0xaaffe4"
# white = "0xcbe3e7"
#
# [colors.bright]
# black = "0x565575"
# red = "0xff5458"
# green = "0x62d196"
# yellow = "0xffb378"
# blue = "0x65b2ff"
# magenta = "0x906cff"
# cyan = "0x63f2f1"
# white = "0xa6b3cc"
#
# solarized

# [colors]
#   # Default colors
# [colors.primary]
#   background = "0x002b36"
#   foreground = "0x839496"

#   # Normal colors
#   [colors.normal]
#   black = "0x073642"
#   red = "0xdc322f"
#   green = "0x859900"
#   yellow = "0xb58900"
#   blue = "0x268bd2"
#   magenta = "0xd33682"
#   cyan = "0x2aa198"
#   white = "0xeee8d5"

#   # Bright colors
#   [colors.bright]
#   black = "0x002b36"
#   red = "0xcb4b16"
#   green = "0x586e75"
#   yellow = "0x657b83"
#   blue = "0x839496"
#   magenta = "0x6c71c4"
#   cyan = "0x93a1a1"
#   white = "0xfdf6e3"

# gruvbox

[colors]
  # Default colors
  [colors.primary]
  # hard contrast: background = "0x1d2021"
  background = "0x282828"
  # soft contrast: background = "0x32302f"
  foreground = "0xebdbb2"

  # Normal colors
  [colors.normal]
  black = "0x282828"
  red = "0xcc241d"
  green = "0x98971a"
  yellow = "0xd79921"
  blue = "0x458588"
  magenta = "0xb16286"
  cyan = "0x689d6a"
  white = "0xa89984"

  # Bright colors
  [colors.bright]
  black = "0x928374"
  red = "0xfb4934"
  green = "0xb8bb26"
  yellow = "0xfabd2f"
  blue = "0x83a598"
  magenta = "0xd3869b"
  cyan = "0x8ec07c"
  white = "0xebdbb2"


